# 🔥 Burn Severity — Benchmark 2: Pipeline vs Standalone
### YOLOv8x-seg · leak-free · runs on H100

Trains two segmentation models on the **identical** source-grouped, leak-free split (seed 42, 205-image test set) used by the classifier benchmark:

1. **1-class localiser** — the segmentation stage of the deployed pipeline (finds the burn region → mask).
2. **3-class standalone** — a segment-and-classify baseline that predicts the degree directly.

**Config (identical to the original run):** 100 epochs · imgsz 640 · batch 8 · AdamW lr 1e-3 · seed 42 · patience 20.
**Data:** `Burn-Benchmark2/dataset/burn-yolo-seg-clean.zip` (on Drive) · **Outputs →** `Burn-Benchmark2/models` + `results`.

In [23]:
# ===== SECTION 1 · SETUP =====
# Mount Drive (all outputs persist there), install Ultralytics, confirm the GPU.
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import subprocess, sys, torch
subprocess.run([sys.executable, "-m", "pip", "-q", "install", "ultralytics==8.3.82"], check=False)

print("torch", torch.__version__, "| CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NONE — switch runtime to H100")

WORK = "/content/drive/MyDrive/Burn-Benchmark2"
print("workspace:", WORK)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
torch 2.11.0+cu128 | CUDA: True
GPU: NVIDIA A100-SXM4-40GB
workspace: /content/drive/MyDrive/Burn-Benchmark2


## Section 2 · Dataset
Unzip the leak-free `burn-yolo-seg-clean` set from Drive to fast local disk and write each `data.yaml`.

In [ ]:
# ===== SECTION 2 · DATASET =====
import os, zipfile, glob
SRC_ZIP = "/content/drive/MyDrive/Burn-Benchmark2/dataset/burn-yolo-seg-clean.zip"
DATA = "/content/burn_yolo_seg"                      # local fast working copy
if not os.path.isdir(DATA):
    with zipfile.ZipFile(SRC_ZIP) as z:
        z.extractall(DATA)
print("extracted ->", sorted(os.listdir(DATA)))

for variant, nc, names in [("1class", 1, ["Burn"]),
                           ("3class", 3, ["Degree1", "Degree2", "Degree3"])]:
    root = os.path.join(DATA, variant)
    with open(os.path.join(root, "data.yaml"), "w") as f:
        f.write(f"path: {root}\ntrain: train/images\nval: valid/images\ntest: test/images\n"
                f"nc: {nc}\nnames: {names}\n")
    counts = {sp: len(glob.glob(f"{root}/{sp}/images/*")) for sp in ["train", "valid", "test"]}
    print(f"  {variant}: {counts}")

extracted -> ['1class', '3class']
  1class: {'train': 2425, 'valid': 206, 'test': 205}
  3class: {'train': 2425, 'valid': 206, 'test': 205}


## Section 3 · Model 1 — 1-class localiser
The segmentation stage of the deployed pipeline. Trains YOLOv8x-seg to find the burn region, saves `best.pt` to Drive.

In [ ]:
# ===== SECTION 3 · MODEL 1 — 1-class localiser =====
import os, shutil
from ultralytics import YOLO
DATA = "/content/burn_yolo_seg"; WORK = "/content/drive/MyDrive/Burn-Benchmark2"
OUT  = f"{WORK}/models/yolov8x-seg_1class_best.pt"

if os.path.exists(OUT):
    print("Model 1 already trained — skipping ->", OUT)
else:
    m1 = YOLO("yolov8x-seg.pt")
    m1.train(data=f"{DATA}/1class/data.yaml", epochs=100, imgsz=640, batch=8,
             optimizer="AdamW", lr0=1e-3, seed=42, patience=20, workers=2,
             project="/content/runs", name="1class", exist_ok=True, verbose=True)
    os.makedirs(f"{WORK}/models", exist_ok=True)
    shutil.copy("/content/runs/1class/weights/best.pt", OUT)
    print("DONE — Model 1 saved ->", OUT)

Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.


100%|██████████| 137M/137M [00:00<00:00, 550MB/s]


New https://pypi.org/project/ultralytics/8.4.104 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
engine/trainer: task=segment, mode=train, model=yolov8x-seg.pt, data=/content/burn_yolo_seg/1class/data.yaml, epochs=100, time=None, patience=20, batch=8, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=2, project=/content/runs, name=1class, exist_ok=True, pretrained=True, optimizer=AdamW, verbose=True, seed=42, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=

100%|██████████| 755k/755k [00:00<00:00, 169MB/s]


Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]                 
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]               
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]           
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]              
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]           
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]              
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]           
  7                  -1  1   3687680  ultralytics

100%|██████████| 5.35M/5.35M [00:00<00:00, 346MB/s]


AMP: checks passed ✅


train: Scanning /content/burn_yolo_seg/1class/train/labels... 2425 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2425/2425 [00:01<00:00, 1372.88it/s]

train: New cache created: /content/burn_yolo_seg/1class/train/labels.cache


albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/burn_yolo_seg/1class/valid/labels... 206 images, 0 backgrounds, 0 corrupt: 100%|██████████| 206/206 [00:00<00:00, 1281.04it/s]

val: New cache created: /content/burn_yolo_seg/1class/valid/labels.cache


Plotting labels to /content/runs/1class/labels.jpg... 
optimizer: AdamW(lr=0.001, momentum=0.937) with parameter groups 106 weight(decay=0.0), 117 weight(decay=0.0005), 116 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/1class
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      1/100      8.37G      1.518      3.261       1.91      1.884          3        640: 100%|██████████| 304/304 [00:53<00:00,  5.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  5.79it/s]

                   all        206        299      0.372       0.41      0.308      0.108      0.339      0.375       0.26     0.0937



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      2/100         8G      1.593      3.279       1.94      1.916          4        640: 100%|██████████| 304/304 [00:48<00:00,  6.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.44it/s]

                   all        206        299      0.408      0.528      0.406      0.181      0.412      0.435      0.382      0.164



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      3/100      8.03G      1.538      3.204      1.818       1.86          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299      0.501      0.522      0.459      0.216      0.491      0.505      0.437      0.196



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      4/100         8G      1.511      3.166      1.792      1.838          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.653      0.478      0.534      0.289      0.635      0.448      0.482      0.246



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      5/100         8G      1.443      3.053      1.689       1.77          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.50it/s]

                   all        206        299      0.642      0.558      0.615       0.33      0.697      0.516      0.588      0.302



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      6/100      8.02G      1.405      2.999      1.634      1.744          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.52it/s]

                   all        206        299      0.701      0.527      0.581        0.3      0.655      0.492      0.516      0.245



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      7/100      8.02G      1.368      2.951      1.583      1.709          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299      0.673      0.531      0.552        0.3      0.642      0.505      0.507      0.257



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      8/100      8.03G      1.377      2.929      1.608      1.718          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.42it/s]

                   all        206        299      0.565      0.565      0.571      0.304      0.519      0.522      0.507      0.254



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      9/100      8.04G      1.344      2.908       1.58      1.713          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.52it/s]

                   all        206        299      0.654      0.525      0.586      0.309      0.644       0.52      0.551      0.272



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     10/100      7.99G      1.308      2.853      1.514      1.667          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.42it/s]

                   all        206        299      0.641      0.582      0.603      0.333      0.643       0.53      0.545      0.278



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     11/100      8.01G      1.305      2.848      1.528       1.67          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.45it/s]

                   all        206        299      0.681      0.534      0.595      0.343      0.626      0.488      0.531      0.297



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     12/100      8.06G       1.29      2.842       1.52      1.666          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299      0.688      0.575      0.598      0.342      0.661      0.548      0.557      0.297



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     13/100      7.99G      1.289      2.805      1.484      1.651          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.49it/s]

                   all        206        299      0.623      0.562      0.575      0.338      0.645      0.538      0.548      0.303



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     14/100      8.03G      1.274      2.783       1.49      1.647          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.55it/s]

                   all        206        299       0.68      0.532       0.61      0.339      0.644      0.502      0.556      0.296



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     15/100      8.02G      1.237      2.715       1.43      1.614          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.694      0.539      0.602      0.343      0.679      0.532      0.561      0.303



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     16/100      8.02G      1.254      2.731       1.44      1.624          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299      0.701      0.548      0.607      0.354      0.668      0.532      0.565      0.305



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     17/100      8.02G      1.236      2.697      1.433      1.608          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.39it/s]

                   all        206        299      0.654      0.625      0.663      0.387      0.692      0.563      0.619       0.35



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     18/100      8.02G      1.255      2.712      1.423      1.632          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.49it/s]

                   all        206        299      0.715      0.592      0.649      0.386      0.714      0.582      0.617      0.343



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     19/100      8.02G      1.264      2.743      1.424      1.629          8        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.46it/s]

                   all        206        299      0.604      0.625      0.626      0.372      0.655      0.526      0.572      0.315



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     20/100      8.04G      1.206      2.662      1.366      1.589          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.49it/s]

                   all        206        299      0.735      0.542      0.625      0.365      0.664      0.532       0.57      0.319



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     21/100      7.99G      1.228      2.641      1.379      1.582          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299      0.755      0.548      0.651        0.4      0.749      0.542      0.623      0.357



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     22/100      7.99G      1.191      2.631       1.34       1.58          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.46it/s]

                   all        206        299      0.714      0.592      0.672      0.407      0.668      0.589      0.634       0.36



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     23/100      8.01G      1.182      2.613      1.322      1.569          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.53it/s]

                   all        206        299      0.719      0.608      0.658      0.401      0.696      0.551      0.611       0.34



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     24/100      8.01G      1.199      2.563      1.327      1.566          6        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.37it/s]

                   all        206        299      0.734      0.582      0.661      0.404      0.698      0.549      0.628      0.355



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     25/100      8.04G       1.19      2.596      1.338      1.562          6        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.50it/s]

                   all        206        299      0.743      0.612      0.687      0.406      0.706      0.582      0.647      0.359



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     26/100      8.02G      1.193      2.583      1.316       1.56          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.59it/s]

                   all        206        299        0.7      0.575      0.642      0.406      0.731      0.572      0.626      0.358



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     27/100         8G      1.162      2.534      1.283      1.547          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.58it/s]

                   all        206        299      0.733      0.614       0.67      0.388      0.704      0.612      0.642      0.372



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     28/100      8.04G      1.153      2.558      1.299      1.545          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.52it/s]

                   all        206        299      0.741      0.609      0.664      0.395      0.679      0.585      0.614      0.351



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     29/100      8.02G      1.162      2.561      1.284      1.538          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.694      0.612      0.662      0.402      0.667      0.609      0.632      0.363



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     30/100      8.02G      1.127      2.497      1.243      1.508          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.59it/s]

                   all        206        299       0.74      0.645      0.694      0.407        0.7      0.609      0.651      0.365



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     31/100      8.04G      1.143      2.504      1.263      1.522          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299      0.749      0.618      0.692      0.429      0.748      0.599      0.681      0.389



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     32/100      7.99G      1.147      2.499      1.269      1.533          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.739      0.644      0.703      0.427      0.716      0.617      0.657      0.377



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     33/100      7.99G      1.148      2.469      1.228      1.519          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.51it/s]

                   all        206        299      0.721      0.605      0.686       0.41      0.685      0.575      0.624      0.349



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     34/100      8.02G      1.127      2.481      1.243      1.515          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.46it/s]

                   all        206        299      0.716      0.632      0.673      0.398      0.701      0.603      0.635       0.35



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     35/100         8G      1.121       2.47      1.217      1.504          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.56it/s]

                   all        206        299      0.729      0.639      0.705       0.44       0.72      0.609      0.665      0.389



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     36/100      8.02G      1.091      2.372      1.199      1.489          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.53it/s]

                   all        206        299       0.69      0.632      0.704      0.429      0.762      0.572      0.663      0.381



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     37/100      8.02G      1.106      2.434      1.199      1.494          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.745      0.624      0.698      0.426      0.725      0.591      0.663      0.386



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     38/100      7.98G      1.091      2.392      1.159      1.491          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.743      0.565      0.687      0.425      0.745      0.555       0.65      0.378



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     39/100      8.02G      1.076      2.354      1.157      1.476          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.754      0.625      0.707      0.429      0.722      0.599      0.659      0.385



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     40/100      8.04G      1.088      2.378      1.147       1.48          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.758      0.609       0.69      0.414       0.74      0.589      0.648      0.363



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     41/100      8.01G      1.077      2.386       1.15      1.475          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.51it/s]

                   all        206        299      0.715      0.669      0.722      0.448      0.699      0.632       0.67      0.398



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     42/100         8G       1.07      2.333      1.129      1.467          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.56it/s]

                   all        206        299      0.753      0.615       0.71      0.438       0.77      0.582      0.672      0.393



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     43/100         8G      1.066      2.356      1.106      1.454          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.721      0.649      0.697      0.427      0.756      0.579      0.665      0.392



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     44/100      8.01G      1.045      2.332      1.117      1.452          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.56it/s]

                   all        206        299      0.691      0.656      0.693      0.425      0.668      0.632      0.653      0.375



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     45/100      7.99G      1.058      2.353      1.124      1.455          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]

                   all        206        299       0.71      0.645      0.701      0.428      0.693      0.619      0.647      0.383



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     46/100      8.02G      1.061      2.327      1.123      1.468          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.724      0.639      0.711      0.422      0.742      0.592       0.67      0.389



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     47/100      8.01G      1.074      2.343      1.126      1.476          7        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.61it/s]

                   all        206        299       0.73      0.662      0.723      0.438      0.714      0.635      0.668      0.386



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     48/100      8.02G      1.036      2.261      1.078      1.435          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.59it/s]

                   all        206        299       0.72       0.61      0.682       0.43      0.702      0.599       0.64      0.378



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     49/100      8.02G      1.045      2.261      1.089      1.452          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.59it/s]

                   all        206        299      0.709      0.642       0.71      0.447      0.765      0.615      0.691      0.406



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     50/100      8.02G      1.019      2.253      1.065       1.42          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.62it/s]

                   all        206        299      0.764      0.619      0.708      0.431      0.733      0.605      0.666      0.384



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     51/100      7.99G      1.022      2.275      1.066      1.431          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.45it/s]

                   all        206        299      0.704      0.645      0.711      0.447      0.693       0.65      0.691      0.393



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     52/100      7.99G      1.011      2.275      1.082      1.415          0        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299       0.76      0.592      0.694      0.441      0.746      0.612      0.675      0.398



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     53/100         8G      1.028      2.266      1.061      1.427          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]

                   all        206        299      0.684      0.652      0.696      0.435      0.684      0.652      0.671      0.392



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     54/100      8.01G      1.011       2.23      1.045       1.42          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.62it/s]

                   all        206        299      0.719      0.649      0.707      0.439      0.703      0.639      0.674      0.399



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     55/100      7.99G      1.011      2.228      1.037      1.414          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]

                   all        206        299      0.705      0.645      0.698      0.446      0.675      0.633      0.667      0.395



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     56/100      7.98G      1.001       2.22      1.026      1.407          9        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.62it/s]

                   all        206        299      0.747      0.666      0.718       0.45      0.752      0.627      0.681      0.394



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     57/100      8.02G     0.9842       2.17      1.025      1.402          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.58it/s]

                   all        206        299      0.762      0.649      0.729      0.448       0.71      0.645      0.682      0.397



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     58/100      8.04G      1.006      2.212      1.011      1.402          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.65it/s]

                   all        206        299       0.81      0.569      0.705      0.427      0.714      0.625      0.682      0.391



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     59/100      8.01G     0.9821      2.198     0.9833      1.398         11        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.61it/s]

                   all        206        299      0.812      0.622      0.728      0.457      0.782      0.599      0.672      0.403



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     60/100      8.05G     0.9675      2.175     0.9852      1.382          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.64it/s]

                   all        206        299      0.764      0.659      0.726      0.447      0.735      0.625      0.674      0.406



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     61/100      8.01G       0.99      2.178     0.9944      1.399          8        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.67it/s]

                   all        206        299      0.745      0.634      0.713      0.442      0.712      0.629      0.669      0.392



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     62/100      8.04G     0.9743      2.141     0.9573      1.385          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.39it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.68it/s]

                   all        206        299      0.766      0.657       0.74      0.444      0.765       0.62       0.69      0.391



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     63/100      8.01G     0.9664      2.136      0.954      1.376          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.65it/s]

                   all        206        299      0.707      0.646      0.702       0.44      0.742      0.639      0.688      0.395



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     64/100      8.01G     0.9491      2.106     0.9374      1.368          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.59it/s]

                   all        206        299      0.717      0.651       0.72      0.439      0.782      0.565      0.678      0.391



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     65/100         8G     0.9631      2.121     0.9313      1.376          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.62it/s]

                   all        206        299      0.807      0.639      0.742      0.449      0.774      0.605      0.688      0.404



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     66/100      8.04G     0.9435      2.114     0.9344      1.363          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.66it/s]

                   all        206        299      0.734      0.675      0.733      0.456       0.72      0.629      0.691      0.409



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     67/100      7.98G     0.9384      2.081     0.9264      1.358          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.52it/s]

                   all        206        299      0.746      0.639      0.696      0.443      0.737      0.602       0.66      0.392



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     68/100         8G     0.9285      2.095      0.922       1.35          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.67it/s]

                   all        206        299       0.81      0.619       0.73      0.463      0.792      0.585      0.685      0.406



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     69/100      8.04G     0.9214      2.052     0.8833      1.336          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]

                   all        206        299      0.791      0.619      0.722      0.443      0.777      0.605      0.685      0.404



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     70/100      7.98G     0.9208      2.075     0.9106       1.35          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.698      0.662      0.716      0.447      0.681      0.651      0.685      0.403



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     71/100         8G     0.9317      2.049     0.9039      1.347          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.66it/s]

                   all        206        299      0.716      0.666      0.713       0.44      0.696      0.643       0.67      0.392



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     72/100      8.06G     0.9104      2.026     0.8849      1.332          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.69it/s]

                   all        206        299      0.733      0.649      0.709      0.443      0.712      0.625      0.672      0.392



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     73/100      8.07G     0.9093      2.051     0.8896      1.334         15        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.65it/s]

                   all        206        299      0.737      0.652      0.742      0.465      0.738      0.622      0.712      0.421



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     74/100      8.04G     0.9018      1.998     0.8698      1.324          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.64it/s]

                   all        206        299      0.828      0.599       0.74      0.455      0.801      0.582       0.69       0.41



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     75/100      8.02G     0.9116       2.02     0.8688      1.335          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.64it/s]

                   all        206        299      0.667       0.69      0.724      0.454      0.807      0.573      0.686      0.404



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     76/100      8.02G     0.8923      2.011      0.859      1.318          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.64it/s]

                   all        206        299       0.68      0.712      0.724      0.447      0.813      0.585      0.697      0.394



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     77/100      7.98G     0.8803      1.978     0.8314      1.304          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.67it/s]

                   all        206        299      0.817      0.614      0.733      0.446      0.804      0.604      0.703      0.397



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     78/100      7.98G      0.886      1.997     0.8399      1.303          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.68it/s]

                   all        206        299      0.806      0.625      0.723       0.44      0.822      0.601      0.696      0.402



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     79/100      8.04G     0.8796      1.976     0.8361      1.305          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]

                   all        206        299       0.76      0.647       0.74      0.449       0.77      0.599      0.686      0.395



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     80/100      8.02G     0.8767      1.959     0.8126      1.307          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.65it/s]

                   all        206        299      0.729      0.642      0.717      0.447      0.788      0.562      0.679      0.395



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     81/100      8.02G     0.8614      1.966     0.7946       1.29          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.61it/s]

                   all        206        299      0.662      0.712      0.715      0.433      0.733      0.599      0.658      0.386



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     82/100      8.01G     0.8548      1.928     0.7782      1.283          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.52it/s]

                   all        206        299       0.72      0.666      0.715      0.451      0.766      0.629      0.684      0.403



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     83/100      8.06G     0.8566      1.944     0.7976      1.293          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.62it/s]

                   all        206        299       0.76      0.647      0.726       0.45      0.762      0.612      0.684      0.402



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     84/100      7.99G     0.8513      1.924     0.7974      1.287          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.66it/s]

                   all        206        299      0.773      0.639      0.735       0.46      0.729      0.647      0.706      0.415



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     85/100      8.03G     0.8403        1.9     0.7825      1.285          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.66it/s]

                   all        206        299      0.832      0.614       0.74      0.462      0.801      0.612      0.703      0.415



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     86/100         8G     0.8486      1.919     0.7855       1.28          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.62it/s]

                   all        206        299      0.822      0.632      0.734      0.457      0.802      0.619      0.707      0.405



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     87/100      8.01G     0.8275      1.873     0.7706      1.261          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.70it/s]

                   all        206        299      0.731      0.679      0.742      0.458      0.812      0.607      0.715      0.412



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     88/100      8.02G     0.8186      1.872     0.7622      1.263          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.68it/s]

                   all        206        299      0.786      0.635      0.741      0.456      0.782      0.632      0.723      0.412



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     89/100         8G     0.8219      1.875     0.7658      1.261          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.65it/s]

                   all        206        299      0.763      0.657      0.737      0.447      0.763      0.649      0.702      0.401



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     90/100      8.02G     0.8109      1.852     0.7287      1.251          6        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.61it/s]

                   all        206        299      0.774      0.679      0.754      0.462      0.788      0.636      0.708      0.414


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     91/100      8.02G      0.779      1.801     0.6667      1.299          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]

                   all        206        299      0.796      0.676      0.756      0.459      0.776      0.662       0.72      0.415



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     92/100      7.99G     0.7546      1.736     0.5992      1.276          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.61it/s]

                   all        206        299       0.75      0.682       0.74      0.461      0.796      0.629       0.72      0.411



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     93/100         8G     0.7428       1.71     0.5954      1.264          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]

                   all        206        299      0.743      0.707      0.741      0.461      0.802      0.637      0.716      0.414
EarlyStopping: Training stopped early as no improvement observed in last 20 epochs. Best results observed at epoch 73, best model saved as best.pt.
To update EarlyStopping(patience=20) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.



93 epochs completed in 1.322 hours.
Optimizer stripped from /content/runs/1class/weights/last.pt, 143.9MB
Optimizer stripped from /content/runs/1class/weights/best.pt, 143.9MB

Validating /content/runs/1class/weights/best.pt...
Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
YOLOv8x-seg summary (fused): 125 layers, 71,721,619 parameters, 0 gradients, 327.9 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  5.06it/s]


                   all        206        299      0.738      0.652      0.742      0.465       0.74      0.622      0.712      0.421
Speed: 0.2ms preprocess, 3.5ms inference, 0.0ms loss, 1.2ms postprocess per image
Results saved to /content/runs/1class
DONE — Model 1 saved -> /content/drive/MyDrive/Burn-Benchmark2/models/yolov8x-seg_1class_best.pt


## Section 4 · Model 2 — 3-class standalone
The segment-and-classify baseline that predicts the burn degree directly (the pipeline's competitor).

In [ ]:
# ===== SECTION 4 · MODEL 2 — 3-class standalone =====
import os, shutil
from ultralytics import YOLO
DATA = "/content/burn_yolo_seg"; WORK = "/content/drive/MyDrive/Burn-Benchmark2"
OUT  = f"{WORK}/models/yolov8x-seg_3class_best.pt"

if os.path.exists(OUT):
    print("Model 2 already trained — skipping ->", OUT)
else:
    m3 = YOLO("yolov8x-seg.pt")
    m3.train(data=f"{DATA}/3class/data.yaml", epochs=100, imgsz=640, batch=8,
             optimizer="AdamW", lr0=1e-3, seed=42, patience=20, workers=2,
             project="/content/runs", name="3class", exist_ok=True, verbose=True)
    shutil.copy("/content/runs/3class/weights/best.pt", OUT)
    print("DONE — Model 2 saved ->", OUT)

New https://pypi.org/project/ultralytics/8.4.104 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
engine/trainer: task=segment, mode=train, model=yolov8x-seg.pt, data=/content/burn_yolo_seg/3class/data.yaml, epochs=100, time=None, patience=20, batch=8, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=2, project=/content/runs, name=3class, exist_ok=True, pretrained=True, optimizer=AdamW, verbose=True, seed=42, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=

train: Scanning /content/burn_yolo_seg/3class/train/labels... 2425 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2425/2425 [00:01<00:00, 1367.31it/s]

train: New cache created: /content/burn_yolo_seg/3class/train/labels.cache


albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/burn_yolo_seg/3class/valid/labels... 206 images, 0 backgrounds, 0 corrupt: 100%|██████████| 206/206 [00:00<00:00, 1191.32it/s]

val: New cache created: /content/burn_yolo_seg/3class/valid/labels.cache


Plotting labels to /content/runs/3class/labels.jpg... 
optimizer: AdamW(lr=0.001, momentum=0.937) with parameter groups 106 weight(decay=0.0), 117 weight(decay=0.0005), 116 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/3class
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      1/100      9.47G       1.51      3.277      2.402      1.876          3        640: 100%|██████████| 304/304 [00:51<00:00,  5.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.228      0.372      0.224      0.109      0.181       0.28      0.145     0.0564



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      2/100      9.49G      1.586      3.261      2.361      1.904          4        640: 100%|██████████| 304/304 [00:48<00:00,  6.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299      0.298      0.435      0.301      0.154      0.309      0.401      0.282       0.13



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      3/100       9.4G       1.53      3.202      2.276      1.855          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.39it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.49it/s]

                   all        206        299      0.311      0.386      0.315      0.172      0.303      0.365      0.299      0.145



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      4/100      9.39G      1.503      3.139      2.206      1.817          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.29it/s]

                   all        206        299      0.399      0.458      0.393      0.214      0.381      0.423      0.354      0.195



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      5/100       9.4G      1.434      3.075      2.102      1.757          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.36it/s]

                   all        206        299      0.389       0.52      0.458      0.267      0.386      0.511      0.449      0.226



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      6/100      9.41G      1.419      3.002      2.031      1.754          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.45it/s]

                   all        206        299      0.465      0.498       0.43      0.251      0.434      0.462      0.401       0.22



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      7/100      9.39G      1.364      2.936      1.979      1.703          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.47it/s]

                   all        206        299      0.499      0.477      0.434      0.257      0.473      0.445      0.404      0.219



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      8/100      9.41G      1.348        2.9      1.958      1.695          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.47it/s]

                   all        206        299      0.508      0.486      0.458      0.278      0.494      0.469      0.438      0.248



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      9/100      9.41G      1.355      2.886      1.941      1.714          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.51it/s]

                   all        206        299      0.463       0.44      0.418      0.247      0.454      0.422      0.401      0.221



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     10/100      9.43G      1.291      2.805       1.88      1.652          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.51it/s]

                   all        206        299       0.55      0.486      0.477      0.291       0.52       0.46      0.439      0.249



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     11/100      9.42G      1.301      2.805      1.889      1.663          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.51it/s]

                   all        206        299      0.504       0.46      0.472      0.296       0.49       0.44      0.437      0.256



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     12/100      9.45G      1.291      2.805      1.877      1.664          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.519      0.512       0.48      0.302      0.504      0.493       0.46       0.27



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     13/100      9.39G      1.284      2.788      1.832      1.647          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.43it/s]

                   all        206        299      0.426      0.473      0.449      0.284      0.413      0.467      0.431      0.257



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     14/100       9.4G      1.272      2.759      1.837      1.641          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.496      0.452      0.458      0.292      0.469       0.48      0.441      0.252



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     15/100      9.39G       1.23      2.689      1.768      1.607          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.30it/s]

                   all        206        299      0.423      0.501      0.457      0.288      0.408      0.475      0.434       0.25



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     16/100       9.4G      1.248      2.675      1.754      1.614          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.51it/s]

                   all        206        299      0.438      0.491      0.467      0.288      0.455      0.446      0.447      0.252



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     17/100      9.41G      1.214      2.623      1.756      1.596          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.53it/s]

                   all        206        299       0.46      0.473      0.459      0.294       0.45      0.463      0.434      0.264



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     18/100      9.38G      1.233      2.685      1.751      1.618          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.35it/s]

                   all        206        299      0.499      0.509      0.501      0.314      0.497      0.498      0.481      0.278



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     19/100      9.45G      1.244      2.682       1.77      1.617          8        640: 100%|██████████| 304/304 [00:47<00:00,  6.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.45it/s]

                   all        206        299      0.558      0.512      0.512      0.317      0.533       0.49      0.487      0.273



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     20/100       9.4G      1.213      2.629      1.703      1.593          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.55it/s]

                   all        206        299      0.425      0.491      0.475      0.305      0.431      0.464      0.451      0.268



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     21/100      9.38G      1.227      2.606      1.696      1.586          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.46it/s]

                   all        206        299      0.481      0.506      0.486       0.32      0.489      0.497      0.476      0.284



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     22/100      9.39G      1.179      2.582      1.664      1.567          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.43it/s]

                   all        206        299      0.693      0.476      0.555      0.362      0.614      0.479      0.535      0.314



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     23/100      9.41G      1.181      2.568      1.631      1.575          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.52it/s]

                   all        206        299      0.521       0.53      0.509      0.319      0.505      0.512      0.491       0.28



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     24/100      9.41G      1.184       2.53      1.632      1.558          6        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.44it/s]

                   all        206        299      0.565      0.487      0.513      0.324      0.562      0.483        0.5      0.298



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     25/100      9.44G      1.176      2.528      1.635      1.542          6        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.50it/s]

                   all        206        299      0.533       0.49      0.509      0.329      0.507      0.509      0.493      0.298



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     26/100      9.41G      1.159       2.54      1.613      1.543          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.59it/s]

                   all        206        299      0.513       0.54       0.53      0.345      0.504      0.531      0.506      0.306



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     27/100      9.43G      1.134      2.481      1.578      1.532          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299      0.508      0.547      0.522       0.34      0.515      0.555      0.516      0.312



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     28/100      9.43G      1.127      2.493      1.578      1.525          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.56it/s]

                   all        206        299       0.66      0.463      0.531      0.341      0.643      0.449      0.498      0.298



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     29/100      9.43G      1.146      2.503      1.577      1.532          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299       0.61      0.469       0.52      0.333      0.608      0.472      0.512      0.303



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     30/100      9.38G      1.127      2.447      1.525      1.509          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.482      0.546      0.524      0.335      0.492      0.534      0.503      0.306



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     31/100      9.43G      1.131      2.466      1.565      1.522          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.46it/s]

                   all        206        299      0.478      0.556      0.521      0.335      0.547      0.481      0.508      0.307



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     32/100      9.41G      1.138      2.461      1.563      1.536          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.42it/s]

                   all        206        299      0.593      0.517      0.545      0.349      0.564      0.519      0.525      0.315



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     33/100      9.44G      1.133      2.431      1.507      1.524          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.51it/s]

                   all        206        299      0.493       0.54      0.517      0.337      0.488      0.526      0.497      0.298



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     34/100      9.41G      1.109      2.423      1.532      1.507          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.39it/s]

                   all        206        299      0.561       0.52      0.536      0.343      0.531      0.504       0.51      0.308



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     35/100       9.4G      1.103      2.427      1.501      1.492          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.49it/s]

                   all        206        299      0.522      0.545      0.543      0.357      0.502      0.524      0.519      0.316



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     36/100      9.41G      1.083      2.352      1.488      1.488          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.45it/s]

                   all        206        299      0.572       0.52      0.546      0.363      0.548      0.516      0.524      0.326



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     37/100      9.41G      1.105       2.42      1.491      1.492          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.47it/s]

                   all        206        299      0.553      0.524      0.533      0.349      0.556      0.512      0.527      0.325



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     38/100      9.39G        1.1      2.369      1.449      1.486          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.52it/s]

                   all        206        299      0.603      0.462      0.519      0.337      0.559      0.467      0.498      0.305



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     39/100      9.43G      1.076      2.343      1.461      1.477          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.47it/s]

                   all        206        299      0.688      0.433      0.546      0.357       0.67      0.427      0.526      0.313



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     40/100      9.41G      1.078      2.342      1.431      1.479          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.50it/s]

                   all        206        299      0.567      0.513      0.554      0.371      0.551      0.502      0.542      0.324



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     41/100      9.41G      1.062      2.339      1.433      1.464          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.53it/s]

                   all        206        299      0.565       0.56      0.574       0.38       0.55       0.54      0.553      0.342



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     42/100      9.41G      1.061       2.31      1.418       1.46          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.47it/s]

                   all        206        299      0.567      0.514      0.567      0.372      0.552      0.502      0.541      0.332



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     43/100      9.41G      1.061      2.333      1.376      1.454          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.583      0.526      0.543      0.356      0.568      0.514       0.52      0.317



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     44/100      9.41G       1.05      2.318      1.411      1.455          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.55it/s]

                   all        206        299      0.625      0.504      0.563      0.376      0.594      0.494      0.534      0.332



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     45/100      9.39G      1.055      2.321      1.372      1.454          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.56it/s]

                   all        206        299      0.549      0.583      0.563      0.373      0.532      0.563      0.536       0.33



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     46/100      9.39G      1.051      2.285      1.356      1.456          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.523      0.581      0.557      0.366      0.514      0.576      0.533      0.332



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     47/100       9.4G       1.06      2.315      1.366      1.462          7        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.49it/s]

                   all        206        299      0.518       0.55      0.557      0.366      0.508      0.545      0.532      0.323



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     48/100      9.39G      1.031       2.22      1.335      1.435          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.594      0.559      0.564      0.371      0.595      0.525      0.548      0.338



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     49/100      9.43G      1.037      2.208      1.308      1.448          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.48it/s]

                   all        206        299      0.592      0.533       0.57      0.366       0.59      0.526      0.546      0.333



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     50/100      9.44G      1.016      2.216      1.293      1.419          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.599      0.563      0.564      0.373      0.606      0.567      0.546      0.327



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     51/100      9.39G      1.008       2.24      1.318      1.421          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.52it/s]

                   all        206        299      0.563      0.572      0.559      0.378      0.556       0.56       0.54      0.329



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     52/100      9.39G      1.002      2.238      1.307      1.407          0        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.545      0.569      0.574      0.379      0.573      0.503      0.545      0.335



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     53/100      9.38G      1.023      2.254      1.301      1.423          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.51it/s]

                   all        206        299      0.624       0.57      0.576      0.377      0.613      0.541      0.553      0.335



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     54/100       9.4G     0.9983        2.2      1.272      1.404          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.53it/s]

                   all        206        299      0.559      0.544      0.547      0.365      0.589      0.522      0.534      0.331



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     55/100      9.39G      1.003      2.195      1.269      1.407          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.50it/s]

                   all        206        299      0.544      0.581      0.568      0.372      0.554      0.558       0.55      0.335



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     56/100       9.4G     0.9905      2.179       1.24      1.397          9        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.602      0.549      0.594      0.378      0.526      0.572      0.548      0.328



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     57/100      9.39G     0.9855      2.143      1.264        1.4          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.539       0.55      0.563      0.377      0.554      0.508      0.544      0.335



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     58/100      9.43G     0.9905      2.174      1.255      1.393          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.49it/s]

                   all        206        299      0.612      0.534      0.584      0.379      0.598      0.533      0.563      0.342



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     59/100      9.42G     0.9773      2.163      1.199      1.388         11        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]

                   all        206        299      0.554      0.571      0.566      0.377      0.621      0.514      0.543      0.338



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     60/100      9.42G     0.9591       2.15      1.204      1.376          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.56it/s]

                   all        206        299      0.601      0.553      0.577      0.385        0.6      0.556      0.567      0.347



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     61/100      9.41G     0.9779      2.139      1.204      1.387          8        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.56it/s]

                   all        206        299      0.699       0.53      0.601      0.397      0.703       0.51      0.587      0.349



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     62/100      9.41G      0.959      2.102      1.175      1.377          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.709      0.483      0.594      0.394        0.7      0.476      0.577      0.351



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     63/100      9.38G     0.9435      2.092      1.134      1.358          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.53it/s]

                   all        206        299      0.617      0.584      0.595      0.397       0.69      0.526      0.575      0.347



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     64/100      9.38G     0.9484      2.074       1.14      1.364          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.636      0.521      0.584      0.385      0.645      0.508      0.567       0.34



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     65/100      9.41G     0.9577      2.089      1.153      1.372          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.55it/s]

                   all        206        299      0.564      0.588      0.583      0.383      0.638      0.515      0.561      0.343



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     66/100      9.45G     0.9388      2.076      1.141      1.356          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.63it/s]

                   all        206        299      0.593      0.565      0.586      0.398      0.587      0.556      0.567      0.356



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     67/100      9.39G     0.9366      2.054      1.139      1.353          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.47it/s]

                   all        206        299      0.645      0.554      0.598      0.393      0.629      0.542      0.571      0.351



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     68/100      9.41G     0.9283      2.057      1.132      1.349          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.657      0.522      0.591      0.395      0.638      0.506      0.566      0.344



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     69/100      9.41G     0.9267      2.027      1.099      1.336          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.53it/s]

                   all        206        299      0.686      0.546      0.594      0.391      0.666      0.528       0.57      0.345



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     70/100      9.38G     0.9196      2.055      1.114      1.339          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.61it/s]

                   all        206        299      0.587      0.567      0.583      0.398      0.615      0.543      0.565      0.356



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     71/100      9.41G     0.9276      2.036      1.092      1.348          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.62it/s]

                   all        206        299      0.603      0.593      0.603      0.399      0.626      0.555      0.575      0.352



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     72/100      9.43G     0.9039      1.999      1.088      1.329          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.683      0.512      0.602        0.4      0.578      0.574      0.581      0.355



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     73/100      9.45G     0.9092      2.027      1.091      1.331         15        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.56it/s]

                   all        206        299      0.611      0.552      0.593      0.395      0.607      0.545      0.585      0.351



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     74/100      9.41G      0.886      1.958      1.065      1.309          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.61it/s]

                   all        206        299      0.597      0.557      0.579      0.377      0.593      0.554      0.559      0.336



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     75/100      9.38G        0.9      1.988      1.058      1.323          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.576      0.592      0.593      0.392      0.653      0.499      0.567      0.349



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     76/100      9.41G     0.8836       1.98      1.049      1.312          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.657       0.52      0.595      0.398      0.648      0.513      0.583      0.345



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     77/100      9.38G     0.8679      1.943       1.01      1.291          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.55it/s]

                   all        206        299      0.636      0.553       0.59      0.392      0.626      0.534      0.574      0.354



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     78/100      9.38G     0.8775      1.964      1.024      1.293          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.558      0.617      0.574      0.381      0.556      0.603      0.562      0.339



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     79/100       9.4G     0.8628      1.937      1.003      1.292          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.62it/s]

                   all        206        299      0.572      0.613      0.593      0.392      0.556      0.597      0.567      0.343



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     80/100      9.38G     0.8632      1.931     0.9816      1.298          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.65it/s]

                   all        206        299      0.643       0.53      0.589      0.391      0.654        0.5      0.571      0.344



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     81/100      9.38G     0.8536      1.929     0.9783      1.285          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.65it/s]

                   all        206        299      0.589      0.537      0.566      0.377      0.615      0.503      0.545      0.329



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     82/100      9.41G     0.8409      1.901     0.9727      1.274          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.58it/s]

                   all        206        299      0.611      0.529      0.571      0.386      0.598      0.516      0.545       0.34



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     83/100      9.42G      0.853      1.913     0.9841      1.288          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.54it/s]

                   all        206        299      0.579      0.597      0.588      0.388      0.554      0.578      0.556      0.338



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     84/100      9.39G     0.8473      1.887     0.9724      1.276          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.56it/s]

                   all        206        299      0.621      0.547      0.601      0.401      0.607      0.536      0.574      0.347



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     85/100      9.39G     0.8347      1.877      0.949      1.275          3        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.62it/s]

                   all        206        299      0.684      0.544      0.615      0.415      0.656      0.541      0.595      0.352



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     86/100       9.4G     0.8336       1.88     0.9412      1.267          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.58it/s]

                   all        206        299      0.629      0.538      0.588      0.397      0.621      0.513      0.567      0.345



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     87/100       9.4G     0.8188      1.836     0.9161      1.253          5        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.594      0.595      0.611      0.405      0.668      0.527      0.584      0.352



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     88/100      9.38G      0.807      1.843     0.9233      1.251          4        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299       0.62      0.553      0.589      0.396      0.597      0.543      0.568      0.343



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     89/100      9.38G     0.8067      1.844     0.9137      1.253          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  6.49it/s]

                   all        206        299       0.58      0.581      0.596      0.394      0.575      0.558      0.572      0.352



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     90/100      9.39G      0.797      1.815     0.8709       1.24          6        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.66it/s]

                   all        206        299      0.631      0.565      0.611      0.409      0.614      0.552      0.586      0.358


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     91/100      9.38G     0.7606      1.772      0.777      1.281          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.37it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.635      0.557      0.585       0.39      0.625      0.548      0.571      0.346



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     92/100      9.39G     0.7328      1.678     0.7102      1.256          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.58it/s]

                   all        206        299      0.647      0.536      0.601        0.4      0.629      0.536      0.582      0.356



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     93/100      9.38G     0.7169      1.661     0.6762      1.243          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.64it/s]

                   all        206        299      0.628      0.562      0.605      0.401      0.548      0.603      0.583      0.354



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     94/100      9.38G     0.7041      1.616      0.645      1.225          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.67it/s]

                   all        206        299      0.659      0.564      0.616      0.408      0.632      0.555      0.588      0.356



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     95/100      9.39G     0.7019      1.635     0.6701      1.226          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.57it/s]

                   all        206        299      0.675      0.562      0.606      0.406      0.655      0.548      0.583      0.359



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     96/100      9.39G     0.6882      1.621     0.6413      1.207          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.695      0.543      0.607      0.409      0.665       0.53      0.581      0.358



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     97/100      9.38G     0.7115      1.644     0.6514      1.232          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.652      0.551      0.606      0.406      0.567      0.619      0.586      0.358



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     98/100      9.38G     0.6663       1.57     0.6134      1.192          2        640: 100%|██████████| 304/304 [00:47<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299      0.646      0.572      0.599        0.4      0.631      0.559      0.575      0.353



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


     99/100      9.39G     0.6793      1.573     0.6024      1.203          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.66it/s]

                   all        206        299      0.709       0.52      0.602      0.406      0.575      0.597      0.581      0.357



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


    100/100      9.38G     0.6585      1.564      0.591       1.18          1        640: 100%|██████████| 304/304 [00:47<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:01<00:00,  6.60it/s]

                   all        206        299       0.68      0.536      0.605      0.405      0.618       0.55       0.58      0.358



100 epochs completed in 1.426 hours.
Optimizer stripped from /content/runs/3class/weights/last.pt, 143.9MB
Optimizer stripped from /content/runs/3class/weights/best.pt, 143.9MB

Validating /content/runs/3class/weights/best.pt...
Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
YOLOv8x-seg summary (fused): 125 layers, 71,723,545 parameters, 0 gradients, 328.0 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:02<00:00,  5.00it/s]


                   all        206        299      0.679      0.544      0.615      0.416      0.656      0.542      0.595      0.352
               Degree1         87        136      0.716      0.529      0.626      0.376      0.695      0.537      0.605      0.322
               Degree2         64         93      0.515       0.43      0.465      0.279      0.488      0.431      0.442       0.24
               Degree3         56         70      0.806      0.671      0.753      0.592      0.785      0.657      0.739      0.495
Speed: 0.2ms preprocess, 3.7ms inference, 0.0ms loss, 1.6ms postprocess per image
Results saved to /content/runs/3class
DONE — Model 2 saved -> /content/drive/MyDrive/Burn-Benchmark2/models/yolov8x-seg_3class_best.pt


## Section 5 · Evaluate + results
Mask mAP (val/test) for both models, plus the 3-class standalone test accuracy for the head-to-head against the pipeline. Saves `benchmark2_results.json` to Drive.

In [ ]:
# ===== SECTION 5 · EVALUATE + RESULTS =====
import os, json, glob
from collections import Counter
from ultralytics import YOLO
DATA = "/content/burn_yolo_seg"; WORK = "/content/drive/MyDrive/Burn-Benchmark2"
results = {}

# mask mAP for both models (val + shared test set)
for variant in ["1class", "3class"]:
    m = YOLO(f"{WORK}/models/yolov8x-seg_{variant}_best.pt")
    val  = m.val(data=f"{DATA}/{variant}/data.yaml", split="val",  verbose=False)
    test = m.val(data=f"{DATA}/{variant}/data.yaml", split="test", verbose=False)
    results[variant] = {"val_mask_map50": float(val.seg.map50),  "val_mask_map": float(val.seg.map),
                        "test_mask_map50": float(test.seg.map50), "test_mask_map": float(test.seg.map)}
    print(variant, results[variant])

# 3-class standalone classification accuracy on the shared 205-image test set
def true_deg(lab):
    cls = [int(l.split()[0]) for l in open(lab) if l.split()]
    return Counter(cls).most_common(1)[0][0] if cls else None
m3 = YOLO(f"{WORK}/models/yolov8x-seg_3class_best.pt")
tdir = f"{DATA}/3class/test"; correct = tot = nodet = 0
for img in glob.glob(f"{tdir}/images/*"):
    base = os.path.splitext(os.path.basename(img))[0]
    lab = f"{tdir}/labels/{base}.txt"
    if not os.path.exists(lab): continue
    td = true_deg(lab)
    if td is None: continue
    r = m3(img, imgsz=640, verbose=False)[0]
    if r.boxes is None or len(r.boxes) == 0:
        pred, nodet = None, nodet + 1
    else:
        confs = r.boxes.conf.cpu().numpy(); pred = int(r.boxes.cls.cpu().numpy()[confs.argmax()])
    correct += int(pred == td); tot += 1
acc = 100 * correct / max(1, tot)
results["3class_standalone_test_accuracy"] = {"acc": acc, "correct": correct, "n": tot, "no_detection": nodet}
print(f"\n3-class standalone test accuracy: {acc:.1f}%  ({correct}/{tot}, {nodet} no-detection)")

os.makedirs(f"{WORK}/results", exist_ok=True)
with open(f"{WORK}/results/benchmark2_results.json", "w") as f:
    json.dump(results, f, indent=2)
print("\nsaved -> Burn-Benchmark2/results/benchmark2_results.json")
print(json.dumps(results, indent=2))

Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
YOLOv8x-seg summary (fused): 125 layers, 71,721,619 parameters, 0 gradients, 327.9 GFLOPs


val: Scanning /content/burn_yolo_seg/1class/valid/labels.cache... 206 images, 0 backgrounds, 0 corrupt: 100%|██████████| 206/206 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:03<00:00,  4.26it/s]


                   all        206        299      0.738      0.652      0.742      0.465      0.743      0.622      0.712       0.42
Speed: 0.7ms preprocess, 5.7ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to runs/segment/val
Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)


val: Scanning /content/burn_yolo_seg/1class/test/labels... 205 images, 0 backgrounds, 0 corrupt: 100%|██████████| 205/205 [00:00<00:00, 1314.00it/s]

val: New cache created: /content/burn_yolo_seg/1class/test/labels.cache



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:03<00:00,  4.14it/s]


                   all        205        294      0.789      0.663      0.765      0.469      0.751      0.663      0.726      0.417
Speed: 0.8ms preprocess, 5.4ms inference, 0.0ms loss, 1.2ms postprocess per image
Results saved to runs/segment/val2
1class {'val_mask_map50': 0.711938496077539, 'val_mask_map': 0.4199379289867088, 'test_mask_map50': 0.7262540929551761, 'test_mask_map': 0.41694065620019305}
Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
YOLOv8x-seg summary (fused): 125 layers, 71,723,545 parameters, 0 gradients, 328.0 GFLOPs


val: Scanning /content/burn_yolo_seg/3class/valid/labels.cache... 206 images, 0 backgrounds, 0 corrupt: 100%|██████████| 206/206 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:03<00:00,  4.01it/s]


                   all        206        299      0.684      0.544      0.615      0.415      0.656      0.542      0.595      0.352
Speed: 0.9ms preprocess, 5.2ms inference, 0.0ms loss, 1.2ms postprocess per image
Results saved to runs/segment/val3
Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)


val: Scanning /content/burn_yolo_seg/3class/test/labels... 205 images, 0 backgrounds, 0 corrupt: 100%|██████████| 205/205 [00:00<00:00, 1317.38it/s]

val: New cache created: /content/burn_yolo_seg/3class/test/labels.cache



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:03<00:00,  4.03it/s]


                   all        205        294      0.687      0.545      0.633      0.397      0.676      0.538      0.603      0.349
Speed: 0.8ms preprocess, 5.2ms inference, 0.0ms loss, 1.3ms postprocess per image
Results saved to runs/segment/val4
3class {'val_mask_map50': 0.5948190138260219, 'val_mask_map': 0.3521864559664328, 'test_mask_map50': 0.602845963933915, 'test_mask_map': 0.34942444995642147}

3-class standalone test accuracy: 78.5%  (161/205, 10 no-detection)

saved -> Burn-Benchmark2/results/benchmark2_results.json
{
  "1class": {
    "val_mask_map50": 0.711938496077539,
    "val_mask_map": 0.4199379289867088,
    "test_mask_map50": 0.7262540929551761,
    "test_mask_map": 0.41694065620019305
  },
  "3class": {
    "val_mask_map50": 0.5948190138260219,
    "val_mask_map": 0.3521864559664328,
    "test_mask_map50": 0.602845963933915,
    "test_mask_map": 0.34942444995642147
  },
  "3class_standalone_test_accuracy": {
    "acc": 78.53658536585365,
    "correct": 161,
    "n

---
# Part B · Complete the honest 3-model head-to-head
Retrain + **save** the two best classifiers (ConvNeXt-Large unmasked, Swin-Tiny masked), compute the **true** end-to-end pipeline (real localiser → predicted mask → Swin, *not* oracle masks), and generate all figures to `Burn-Benchmark2/figures/`.
*(Section 6 below sets up the classifier data + shared training helper.)*

In [ ]:
# ===== SECTION 6 · CLASSIFIER DATA + SHARED HELPERS =====
import subprocess, sys, os, glob, zipfile
subprocess.run([sys.executable, "-m", "pip", "-q", "install", "timm==1.0.11", "seaborn", "scikit-learn"], check=False)
import torch, torch.nn as nn, numpy as np, timm
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
DEV = "cuda" if torch.cuda.is_available() else "cpu"
WORK = "/content/drive/MyDrive/Burn-Benchmark2"; os.makedirs(f"{WORK}/figures", exist_ok=True)
IMAGENET = ([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])

CLS = "/content/burn_4cond"
if not os.path.isdir(CLS):
    with zipfile.ZipFile(f"{WORK}/dataset/burn-clean-4cond.zip") as z: z.extractall(CLS)
CLS_ROOT = CLS
for r, ds, fs in os.walk(CLS):
    if os.path.isdir(os.path.join(r, "unmasked")) and os.path.isdir(os.path.join(r, "masked")):
        CLS_ROOT = r; break
print("classifier root:", CLS_ROOT, sorted(os.listdir(CLS_ROOT)))

def tfm(train):
    ops = [transforms.Resize((224, 224))]
    if train: ops += [transforms.RandomHorizontalFlip(), transforms.ColorJitter(0.2, 0.2, 0.2), transforms.RandomRotation(10)]
    return transforms.Compose(ops + [transforms.ToTensor(), transforms.Normalize(*IMAGENET)])

def train_classifier(arch_id, cond, seed=42, epochs=30):
    torch.manual_seed(seed); np.random.seed(seed)
    root = f"{CLS_ROOT}/{cond}"
    tr = datasets.ImageFolder(f"{root}/train", tfm(True)); va = datasets.ImageFolder(f"{root}/valid", tfm(False)); te = datasets.ImageFolder(f"{root}/test", tfm(False))
    cnt = np.bincount([y for _, y in tr.samples], minlength=3).astype(float)
    w = torch.tensor(cnt.sum() / (3 * np.clip(cnt, 1, None)), dtype=torch.float32, device=DEV)
    dltr = DataLoader(tr, 16, shuffle=True, num_workers=2, drop_last=True); dlva = DataLoader(va, 32, num_workers=2); dlte = DataLoader(te, 32, num_workers=2)
    model = timm.create_model(arch_id, pretrained=True, num_classes=3).to(DEV)
    opt = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2); sch = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=epochs)
    crit = nn.CrossEntropyLoss(weight=w); scaler = torch.cuda.amp.GradScaler(); best_va = -1; best = None; bad = 0
    for ep in range(epochs):
        model.train()
        for x, y in dltr:
            x, y = x.to(DEV), y.to(DEV); opt.zero_grad()
            with torch.cuda.amp.autocast(): loss = crit(model(x), y)
            scaler.scale(loss).backward(); scaler.step(opt); scaler.update()
        sch.step(); model.eval(); c = t = 0
        with torch.no_grad():
            for x, y in dlva: c += (model(x.to(DEV)).argmax(1).cpu() == y).sum().item(); t += len(y)
        if c / t > best_va: best_va = c / t; best = {k: v.cpu().clone() for k, v in model.state_dict().items()}; bad = 0
        else:
            bad += 1
            if bad >= 5: break
    model.load_state_dict(best); model.eval(); ys = []; ps = []
    with torch.no_grad():
        for x, y in dlte: ps += model(x.to(DEV)).argmax(1).cpu().tolist(); ys += y.tolist()
    acc = 100 * float(np.mean(np.array(ys) == np.array(ps)))
    return model, ys, ps, acc, te.classes
print("helpers ready · device:", DEV)

classifier root: /content/burn_4cond ['cropped', 'masked', 'maskedcrop', 'unmasked']
helpers ready · device: cuda


In [ ]:
# ===== SECTION 7 · RETRAIN + SAVE THE TWO BEST CLASSIFIERS =====
import torch, os, json, numpy as np
from torch.utils.data import DataLoader
from torchvision import datasets
from sklearn.metrics import confusion_matrix
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt, seaborn as sns
LBL = ["1st", "2nd", "3rd"]

def eval_saved(arch, cond, path):
    m = timm.create_model(arch, pretrained=False, num_classes=3)
    m.load_state_dict(torch.load(path, map_location=DEV)); m = m.to(DEV).eval()
    te = datasets.ImageFolder(f"{CLS_ROOT}/{cond}/test", tfm(False)); dl = DataLoader(te, 32, num_workers=2)
    ys, ps = [], []
    with torch.no_grad():
        for x, y in dl: ps += m(x.to(DEV)).argmax(1).cpu().tolist(); ys += y.tolist()
    return ys, ps, 100 * float(np.mean(np.array(ys) == np.array(ps)))

CFG = [("convnext_large", "unmasked", "convnext_large_unmasked", "Standalone classifier"),
       ("swin_tiny_patch4_window7_224", "masked", "swin_tiny_masked", "Pipeline classifier")]
cls_results = {}
for arch, cond, tag, label in CFG:
    out = f"{WORK}/models/{tag}.pth"
    if os.path.exists(out):
        ys, ps, acc = eval_saved(arch, cond, out); print(f"{label}: loaded {tag} — TEST {acc:.1f}%")
    else:
        print(f"training {label} ({arch} / {cond}) ...", flush=True)
        model, ys, ps, acc, _ = train_classifier(arch, cond)
        torch.save(model.state_dict(), out); print(f"{label}: trained {tag} — TEST {acc:.1f}% -> saved")
    cm = confusion_matrix(ys, ps, labels=[0, 1, 2])
    cls_results[tag] = {"arch": arch, "cond": cond, "test_acc": acc, "cm": cm.tolist()}
    plt.figure(figsize=(3.8, 3.2)); sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=LBL, yticklabels=LBL)
    plt.title(f"{label}\n{arch} ({cond}) — {acc:.1f}%"); plt.ylabel("True"); plt.xlabel("Predicted"); plt.tight_layout()
    plt.savefig(f"{WORK}/figures/cm_{tag}.png", dpi=150); plt.close()
os.makedirs(f"{WORK}/results", exist_ok=True)
json.dump(cls_results, open(f"{WORK}/results/classifier_results.json", "w"), indent=2)
print("\nclassifier results:", {k: round(v['test_acc'], 1) for k, v in cls_results.items()})

training Standalone classifier (convnext_large / unmasked) ...


model.safetensors: reconstructing file:   0%|          |  0.00B /  791MB            

model.safetensors: downloading bytes:           |  0.00B            

Standalone classifier: trained convnext_large_unmasked — TEST 82.4% -> saved
training Pipeline classifier (swin_tiny_patch4_window7_224 / masked) ...


model.safetensors: reconstructing file:   0%|          |  0.00B /  114MB            

model.safetensors: downloading bytes:           |  0.00B            

Pipeline classifier: trained swin_tiny_masked — TEST 83.9% -> saved

classifier results: {'convnext_large_unmasked': 82.4, 'swin_tiny_masked': 83.9}


In [ ]:
# ===== SECTION 8 · TRUE END-TO-END PIPELINE (real localiser -> mask -> Swin) =====
import cv2, glob, os, json, numpy as np, torch, timm
from PIL import Image
from ultralytics import YOLO
from collections import Counter
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt, seaborn as sns
LBL = ["1st", "2nd", "3rd"]

yolo = YOLO(f"{WORK}/models/yolov8x-seg_1class_best.pt")            # the real localiser
swin = timm.create_model("swin_tiny_patch4_window7_224", pretrained=False, num_classes=3)
swin.load_state_dict(torch.load(f"{WORK}/models/swin_tiny_masked.pth", map_location=DEV)); swin = swin.to(DEV).eval()

def true_deg(lab):
    c = [int(l.split()[0]) for l in open(lab) if l.split()]
    return Counter(c).most_common(1)[0][0] if c else None

def pipe_pred(img_path):
    bgr = cv2.imread(img_path); r = yolo(bgr, imgsz=640, verbose=False)[0]
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    if r.masks is None or len(r.boxes) == 0: return None            # localiser found nothing
    conf = r.boxes.conf.cpu().numpy(); mk = r.masks.data[int(np.argmax(conf))].cpu().numpy()
    mk = cv2.resize(mk, (rgb.shape[1], rgb.shape[0])); masked = rgb * (mk > 0.1).astype(np.uint8)[:, :, None]
    x = tfm(False)(Image.fromarray(masked.astype(np.uint8))).unsqueeze(0).to(DEV)
    with torch.no_grad(): return int(swin(x).argmax(1))

tdir = "/content/burn_yolo_seg/3class/test"; ys, ps, nodet = [], [], 0
for img in glob.glob(f"{tdir}/images/*"):
    base = os.path.splitext(os.path.basename(img))[0]; lab = f"{tdir}/labels/{base}.txt"
    if not os.path.exists(lab): continue
    td = true_deg(lab)
    if td is None: continue
    pr = pipe_pred(img)
    if pr is None: nodet += 1; pr = -1                              # no-detection = error (kept in denominator)
    ys.append(td); ps.append(pr)
ys, ps = np.array(ys), np.array(ps); n = len(ys); correct = int((ys == ps).sum()); acc = 100 * correct / n
print(f"TRUE PIPELINE (localiser -> mask -> Swin-Tiny) TEST acc: {acc:.1f}%  ({correct}/{n}, {nodet} no-detection = errors)")
cm = confusion_matrix(ys, np.where(ps < 0, 3, ps), labels=[0, 1, 2, 3])[:3]
plt.figure(figsize=(4.4, 3.2)); sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', xticklabels=LBL + ["no-det"], yticklabels=LBL)
plt.title(f"True pipeline (real masks) — {acc:.1f}%"); plt.ylabel("True"); plt.xlabel("Predicted"); plt.tight_layout()
plt.savefig(f"{WORK}/figures/cm_true_pipeline.png", dpi=150); plt.close()
json.dump({"true_pipeline_test_acc": acc, "n": n, "correct": correct, "no_detection": nodet},
          open(f"{WORK}/results/true_pipeline_results.json", "w"), indent=2)
print("saved -> true_pipeline_results.json + confusion matrix")

TRUE PIPELINE (localiser -> mask -> Swin-Tiny) TEST acc: 79.0%  (162/205, 10 no-detection = errors)
saved -> true_pipeline_results.json + confusion matrix


In [ ]:
# ===== SECTION 9 · HEAD-TO-HEAD CHART + YOLO FIGURES =====
import json, os, numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO
cls  = json.load(open(f"{WORK}/results/classifier_results.json"))
pipe = json.load(open(f"{WORK}/results/true_pipeline_results.json"))
b2   = json.load(open(f"{WORK}/results/benchmark2_results.json"))
N = pipe["n"]

def wilson(k, n, z=1.96):
    p = k / n; d = 1 + z*z/n; c = (p + z*z/(2*n)) / d
    h = z * np.sqrt(p*(1-p)/n + z*z/(4*n*n)) / d
    return 100*(c-h), 100*(c+h)

rows = [("Standalone\nYOLOv8x-seg", b2["3class_standalone_test_accuracy"]["acc"], b2["3class_standalone_test_accuracy"]["correct"]),
        ("Pipeline\nloc->Swin",     pipe["true_pipeline_test_acc"], pipe["correct"]),
        ("Standalone\nConvNeXt-L",  cls["convnext_large_unmasked"]["test_acc"], round(cls["convnext_large_unmasked"]["test_acc"]/100*N))]
names = [r[0] for r in rows]; vals = [r[1] for r in rows]
lo = [wilson(r[2], N)[0] for r in rows]; hi = [wilson(r[2], N)[1] for r in rows]
err = [[v-l for v, l in zip(vals, lo)], [h-v for v, h in zip(vals, hi)]]
fig, ax = plt.subplots(figsize=(6, 4.2))
ax.bar(names, vals, color=["#d95f02", "#1b9e77", "#7570b3"], yerr=err, capsize=6)
for i, v in enumerate(vals): ax.text(i, v + 1.4, f"{v:.1f}%", ha='center', fontweight='bold')
ax.set_ylabel("Test accuracy (%)"); ax.set_ylim(55, 95)
ax.set_title(f"Burn-degree head-to-head — leak-free test (N={N}), 95% Wilson CI")
plt.tight_layout(); plt.savefig(f"{WORK}/figures/head_to_head.png", dpi=160); plt.close()
print("head-to-head chart saved. numbers:", [(n_, round(v,1)) for n_, v in zip(names, vals)])

# regenerate YOLO confusion matrices + PR curves from the saved best.pt
for variant in ["1class", "3class"]:
    YOLO(f"{WORK}/models/yolov8x-seg_{variant}_best.pt").val(
        data=f"/content/burn_yolo_seg/{variant}/data.yaml", split="test", plots=True,
        project=f"{WORK}/figures", name=f"yolo_{variant}_test", exist_ok=True, verbose=False)
print("\nALL FIGURES in Burn-Benchmark2/figures/:", sorted(os.listdir(f"{WORK}/figures")))

head-to-head chart saved. numbers: [('Standalone\nYOLOv8x-seg', 78.5), ('Pipeline\nloc->Swin', 79.0), ('Standalone\nConvNeXt-L', 82.4)]
Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
YOLOv8x-seg summary (fused): 125 layers, 71,721,619 parameters, 0 gradients, 327.9 GFLOPs


val: Scanning /content/burn_yolo_seg/1class/test/labels.cache... 205 images, 0 backgrounds, 0 corrupt: 100%|██████████| 205/205 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:03<00:00,  4.24it/s]


                   all        205        294      0.789      0.663      0.765      0.469      0.751      0.663      0.726      0.417
Speed: 0.8ms preprocess, 5.2ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to /content/drive/MyDrive/Burn-Benchmark2/figures/yolo_1class_test
Ultralytics 8.3.82 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-40GB, 40441MiB)
YOLOv8x-seg summary (fused): 125 layers, 71,723,545 parameters, 0 gradients, 328.0 GFLOPs


val: Scanning /content/burn_yolo_seg/3class/test/labels.cache... 205 images, 0 backgrounds, 0 corrupt: 100%|██████████| 205/205 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 13/13 [00:03<00:00,  4.03it/s]


                   all        205        294      0.687      0.545      0.633      0.397      0.676      0.538      0.603      0.349
Speed: 0.7ms preprocess, 5.2ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to /content/drive/MyDrive/Burn-Benchmark2/figures/yolo_3class_test

ALL FIGURES in Burn-Benchmark2/figures/: ['cm_convnext_large_unmasked.png', 'cm_swin_tiny_masked.png', 'cm_true_pipeline.png', 'head_to_head.png', 'yolo_1class_test', 'yolo_3class_test']


---
## Section 10 · External generalization test (clean 319-image set)
Runs all three models on the leak-verified external set (independent sources, 226 BIAC-duplicate images removed). Reports accuracy + **balanced** accuracy (the set is imbalanced) + confusion matrices → a second generalization data point alongside BIP_US. Inference only, ~3–5 min.

In [ ]:
# ===== SECTION 10 · EXTERNAL GENERALIZATION EVAL (clean 319-image set) =====
import os, glob, json, zipfile, numpy as np, cv2, torch, timm
from PIL import Image
from ultralytics import YOLO
from collections import Counter
from sklearn.metrics import confusion_matrix, balanced_accuracy_score
import matplotlib.pyplot as plt, seaborn as sns
WORK = "/content/drive/MyDrive/Burn-Benchmark2"; LBL = ["1st", "2nd", "3rd"]

EXT = "/content/external"
if not os.path.isdir(EXT):
    with zipfile.ZipFile(f"{WORK}/dataset/burn-external-test-clean.zip") as z: z.extractall(EXT)
IMG = None
for r, ds, fs in os.walk(EXT):
    if os.path.isdir(os.path.join(r, "images")) and os.path.isdir(os.path.join(r, "labels")): IMG = r; break
print("external root:", IMG, "| images:", len(glob.glob(f"{IMG}/images/*")))

yolo3 = YOLO(f"{WORK}/models/yolov8x-seg_3class_best.pt")
yolo1 = YOLO(f"{WORK}/models/yolov8x-seg_1class_best.pt")
swin = timm.create_model("swin_tiny_patch4_window7_224", pretrained=False, num_classes=3)
swin.load_state_dict(torch.load(f"{WORK}/models/swin_tiny_masked.pth", map_location=DEV)); swin = swin.to(DEV).eval()
cnx = timm.create_model("convnext_large", pretrained=False, num_classes=3)
cnx.load_state_dict(torch.load(f"{WORK}/models/convnext_large_unmasked.pth", map_location=DEV)); cnx = cnx.to(DEV).eval()

def true_deg(lab):
    c = [int(l.split()[0]) for l in open(lab) if l.split()]; return Counter(c).most_common(1)[0][0] if c else None
def yolo_pred(m, bgr):
    r = m(bgr, imgsz=640, verbose=False)[0]
    if r.boxes is None or len(r.boxes) == 0: return -1
    cf = r.boxes.conf.cpu().numpy(); return int(r.boxes.cls.cpu().numpy()[cf.argmax()])
def pipe_pred(bgr):
    r = yolo1(bgr, imgsz=640, verbose=False)[0]; rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    if r.masks is None or len(r.boxes) == 0: return -1
    cf = r.boxes.conf.cpu().numpy(); mk = r.masks.data[int(cf.argmax())].cpu().numpy()
    mk = cv2.resize(mk, (rgb.shape[1], rgb.shape[0])); masked = rgb * (mk > 0.1).astype(np.uint8)[:, :, None]
    x = tfm(False)(Image.fromarray(masked.astype(np.uint8))).unsqueeze(0).to(DEV)
    with torch.no_grad(): return int(swin(x).argmax(1))
def cnx_pred(bgr):
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB); x = tfm(False)(Image.fromarray(rgb)).unsqueeze(0).to(DEV)
    with torch.no_grad(): return int(cnx(x).argmax(1))

yt = []; P = {"yolo": [], "pipe": [], "cnx": []}
for img in glob.glob(f"{IMG}/images/*"):
    base = os.path.splitext(os.path.basename(img))[0]; lab = f"{IMG}/labels/{base}.txt"
    if not os.path.exists(lab): continue
    td = true_deg(lab)
    if td is None: continue
    bgr = cv2.imread(img)
    if bgr is None: continue
    yt.append(td)
    P["yolo"].append(yolo_pred(yolo3, bgr)); P["pipe"].append(pipe_pred(bgr)); P["cnx"].append(cnx_pred(bgr))
yt = np.array(yt); N = len(yt)
ext = {}
for key, name, cmap in [("cnx", "Standalone ConvNeXt-L", "Oranges"), ("pipe", "Pipeline loc->Swin", "Oranges"), ("yolo", "Standalone YOLOv8-seg", "Oranges")]:
    pp = np.array(P[key]); acc = 100 * float((pp == yt).mean())
    bal = 100 * balanced_accuracy_score(yt, np.where(pp < 0, 99, pp))
    ext[key] = {"name": name, "acc": acc, "balanced_acc": bal, "n": int(N), "correct": int((pp == yt).sum()),
                "no_detection": int((pp < 0).sum())}
    cm = confusion_matrix(yt, np.where(pp < 0, 3, pp), labels=[0, 1, 2, 3])[:3]
    plt.figure(figsize=(4.4, 3.2)); sns.heatmap(cm, annot=True, fmt='d', cmap=cmap, xticklabels=LBL + ["no-det"], yticklabels=LBL)
    plt.title(f"EXTERNAL: {name} — {acc:.1f}% (bal {bal:.1f}%)"); plt.ylabel("True"); plt.xlabel("Predicted"); plt.tight_layout()
    plt.savefig(f"{WORK}/figures/ext_cm_{key}.png", dpi=150); plt.close()
    print(f"EXTERNAL {name}: acc {acc:.1f}%  | balanced {bal:.1f}%  | {int((pp<0).sum())} no-detection")
json.dump({"N": int(N), "per_degree": {LBL[k]: int((yt == k).sum()) for k in [0, 1, 2]}, "models": ext},
          open(f"{WORK}/results/external_eval_results.json", "w"), indent=2)
print("\nsaved -> external_eval_results.json + external confusion matrices. N =", N,
      "| degree dist:", {LBL[k]: int((yt == k).sum()) for k in [0, 1, 2]})

external root: /content/external | images: 319
EXTERNAL Standalone ConvNeXt-L: acc 74.3%  | balanced 78.7%  | 0 no-detection
EXTERNAL Pipeline loc->Swin: acc 54.2%  | balanced 54.7%  | 66 no-detection


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:2524: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:2524: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")


EXTERNAL Standalone YOLOv8-seg: acc 58.0%  | balanced 65.5%  | 55 no-detection

saved -> external_eval_results.json + external confusion matrices. N = 319 | degree dist: {'1st': 139, '2nd': 157, '3rd': 23}


---
## Section 11 · Robust pipeline (fair-chance: low threshold + full-frame fallback)
Gives the pipeline its best honest shot, matching the deployed app: lower the localiser confidence threshold, and if it *still* detects nothing, fall back to classifying the **full image** with Swin (never auto-fail). Evaluated on **both** internal (205) and external (319). Reported alongside the strict pipeline for full transparency (no bias). Inference only.

In [ ]:
# ===== SECTION 11 · ROBUST PIPELINE (low localiser threshold + full-frame fallback) =====
import os, glob, json, numpy as np, cv2, torch, timm
from PIL import Image
from ultralytics import YOLO
from collections import Counter
from sklearn.metrics import balanced_accuracy_score
WORK = "/content/drive/MyDrive/Burn-Benchmark2"; LBL = ["1st", "2nd", "3rd"]
yolo1 = YOLO(f"{WORK}/models/yolov8x-seg_1class_best.pt")
swin = timm.create_model("swin_tiny_patch4_window7_224", pretrained=False, num_classes=3)
swin.load_state_dict(torch.load(f"{WORK}/models/swin_tiny_masked.pth", map_location=DEV)); swin = swin.to(DEV).eval()

def classify_full(rgb):
    x = tfm(False)(Image.fromarray(rgb.astype(np.uint8))).unsqueeze(0).to(DEV)
    with torch.no_grad(): return int(swin(x).argmax(1))

def robust_pipe(bgr, conf=0.05):
    r = yolo1(bgr, imgsz=640, conf=conf, verbose=False)[0]; rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    if r.masks is None or len(r.boxes) == 0:
        return classify_full(rgb), True                       # fallback: full image -> Swin
    cf = r.boxes.conf.cpu().numpy(); mk = r.masks.data[int(cf.argmax())].cpu().numpy()
    mk = cv2.resize(mk, (rgb.shape[1], rgb.shape[0])); masked = rgb * (mk > 0.1).astype(np.uint8)[:, :, None]
    return classify_full(masked), False

def true_deg(lab):
    c = [int(l.split()[0]) for l in open(lab) if l.split()]; return Counter(c).most_common(1)[0][0] if c else None

def eval_set(img_dir, lab_dir):
    yt, pp, fb = [], [], 0
    for img in glob.glob(f"{img_dir}/*"):
        base = os.path.splitext(os.path.basename(img))[0]; lab = f"{lab_dir}/{base}.txt"
        if not os.path.exists(lab): continue
        td = true_deg(lab)
        if td is None: continue
        bgr = cv2.imread(img)
        if bgr is None: continue
        p, used = robust_pipe(bgr); yt.append(td); pp.append(p); fb += int(used)
    yt, pp = np.array(yt), np.array(pp); n = len(yt)
    return 100 * float((pp == yt).mean()), 100 * balanced_accuracy_score(yt, pp), n, fb

res = {}
sets = {"internal": ("/content/burn_yolo_seg/3class/test/images", "/content/burn_yolo_seg/3class/test/labels"),
        "external": ("/content/external/images", "/content/external/labels")}
for tag, (idir, ldir) in sets.items():
    acc, bal, n, fb = eval_set(idir, ldir)
    res[tag] = {"robust_pipeline_acc": acc, "balanced_acc": bal, "n": n, "fallback_used": fb}
    print(f"ROBUST PIPELINE {tag}: acc {acc:.1f}%  | balanced {bal:.1f}%  (N={n}, fallback used on {fb} imgs)")
json.dump(res, open(f"{WORK}/results/robust_pipeline_results.json", "w"), indent=2)
print("\nsaved -> robust_pipeline_results.json")

ROBUST PIPELINE internal: acc 81.5%  | balanced 80.9%  (N=205, fallback used on 0 imgs)
ROBUST PIPELINE external: acc 69.9%  | balanced 66.3%  (N=319, fallback used on 1 imgs)

saved -> robust_pipeline_results.json


---
## Section 12 · Multi-seed robustness (3 seeds) — the key comparison
Retrains ConvNeXt-Large (standalone) + Swin-Tiny (pipeline classifier) at seeds 0/1/2, re-evaluates the **standalone classifier** and the **robust pipeline** (localiser fixed) on internal (205) + external (319), and reports **mean ± SD**. This turns "single run, CIs overlap" into a statistically credible comparison. Longest run (~1 h) — keep the tab in front.

In [ ]:
# ===== SECTION 12 · MULTI-SEED ROBUSTNESS (3 seeds: classifier vs robust pipeline) =====
# Resumable: saves after each seed, skips seeds already done on re-run.
import os, json, glob, numpy as np, cv2, torch
from PIL import Image
from ultralytics import YOLO
from collections import Counter, defaultdict
from sklearn.metrics import balanced_accuracy_score
WORK = "/content/drive/MyDrive/Burn-Benchmark2"
yolo1 = YOLO(f"{WORK}/models/yolov8x-seg_1class_best.pt")   # localiser fixed across seeds
RESF = f"{WORK}/results/multiseed_results.json"

def true_deg(lab):
    c = [int(l.split()[0]) for l in open(lab) if l.split()]; return Counter(c).most_common(1)[0][0] if c else None
def pairs(idir, ldir):
    out = []
    for img in glob.glob(f"{idir}/*"):
        b = os.path.splitext(os.path.basename(img))[0]; lab = f"{ldir}/{b}.txt"
        if os.path.exists(lab):
            td = true_deg(lab)
            if td is not None: out.append((img, td))
    return out
INT = pairs("/content/burn_yolo_seg/3class/test/images", "/content/burn_yolo_seg/3class/test/labels")
EXT = pairs("/content/external/images", "/content/external/labels")
IMGS = {f: cv2.imread(f) for f, _ in INT + EXT}

def clf_pred(model, bgr):
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB); x = tfm(False)(Image.fromarray(rgb)).unsqueeze(0).to(DEV)
    with torch.no_grad(): return int(model(x).argmax(1))
def pipe_pred(swin, bgr, conf=0.05):
    r = yolo1(bgr, imgsz=640, conf=conf, verbose=False)[0]; rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    if r.masks is None or len(r.boxes) == 0:
        img = rgb
    else:
        cf = r.boxes.conf.cpu().numpy(); mk = r.masks.data[int(cf.argmax())].cpu().numpy()
        mk = cv2.resize(mk, (rgb.shape[1], rgb.shape[0])); img = rgb * (mk > 0.1).astype(np.uint8)[:, :, None]
    x = tfm(False)(Image.fromarray(img.astype(np.uint8))).unsqueeze(0).to(DEV)
    with torch.no_grad(): return int(swin(x).argmax(1))
def score(ps, predfn):
    yt = np.array([t for _, t in ps]); pp = np.array([predfn(IMGS[f]) for f, _ in ps])
    return 100 * float((pp == yt).mean()), 100 * balanced_accuracy_score(yt, pp)

acc = defaultdict(list); done = []
if os.path.exists(RESF):
    prev = json.load(open(RESF))
    if "_raw" in prev:
        acc = defaultdict(list, {k: list(v) for k, v in prev["_raw"].items()}); done = prev.get("_seeds_done", [])
        print("resuming; seeds already done:", done)

for seed in [0, 1, 2]:
    if seed in done: print(f"seed {seed} done — skip"); continue
    print(f"seed {seed}: training classifiers ...", flush=True)
    cnx, *_ = train_classifier("convnext_large", "unmasked", seed=seed)
    swin, *_ = train_classifier("swin_tiny_patch4_window7_224", "masked", seed=seed)
    cnx.eval(); swin.eval()
    for tag, ps in [("int", INT), ("ext", EXT)]:
        a, b = score(ps, lambda bgr: clf_pred(cnx, bgr));   acc[f"clf_{tag}"].append(a);  acc[f"clf_{tag}_bal"].append(b)
        a, b = score(ps, lambda bgr: pipe_pred(swin, bgr)); acc[f"pipe_{tag}"].append(a); acc[f"pipe_{tag}_bal"].append(b)
    done.append(seed)
    json.dump({"_raw": dict(acc), "_seeds_done": done}, open(RESF, "w"))
    print(f"  seed {seed}: clf_int {acc['clf_int'][-1]:.1f} pipe_int {acc['pipe_int'][-1]:.1f} | "
          f"clf_ext {acc['clf_ext'][-1]:.1f} pipe_ext {acc['pipe_ext'][-1]:.1f}  [saved]", flush=True)

summ = {k: {"mean": float(np.mean(v)), "sd": float(np.std(v)), "seeds": list(v)} for k, v in acc.items()}
summ["_raw"] = dict(acc); summ["_seeds_done"] = done
json.dump(summ, open(RESF, "w"), indent=2)
print("\n=== MULTI-SEED (mean ± SD over seeds", done, ") ===")
for k in ["clf_int", "pipe_int", "clf_ext", "pipe_ext", "clf_ext_bal", "pipe_ext_bal"]:
    if k in summ: print(f"  {k:14s}: {summ[k]['mean']:.1f} ± {summ[k]['sd']:.1f}")
print("saved -> multiseed_results.json")

seed 0: training classifiers ...
  seed 0: clf_int 82.0 pipe_int 78.0 | clf_ext 76.8 pipe_ext 70.5  [saved]
seed 1: training classifiers ...
  seed 1: clf_int 82.4 pipe_int 78.5 | clf_ext 74.9 pipe_ext 74.3  [saved]
seed 2: training classifiers ...
  seed 2: clf_int 83.4 pipe_int 80.0 | clf_ext 78.1 pipe_ext 75.2  [saved]

=== MULTI-SEED (mean ± SD over seeds [0, 1, 2] ) ===
  clf_int       : 82.6 ± 0.6
  pipe_int      : 78.9 ± 0.8
  clf_ext       : 76.6 ± 1.3
  pipe_ext      : 73.4 ± 2.0
  clf_ext_bal   : 80.1 ± 1.5
  pipe_ext_bal  : 77.9 ± 2.7
saved -> multiseed_results.json


---
## Section 13 · Efficiency / timing table
Per-image inference time for each stage and the full pipeline on the A100 — a stated benchmark goal and a professional touch for the deployed-system story. Fast (~1 min).

In [ ]:
# ===== SECTION 13 · EFFICIENCY / TIMING (per-stage, A100) =====
import time, glob, json, numpy as np, cv2, torch, timm
from PIL import Image
from ultralytics import YOLO
WORK = "/content/drive/MyDrive/Burn-Benchmark2"
yolo1 = YOLO(f"{WORK}/models/yolov8x-seg_1class_best.pt")
yolo3 = YOLO(f"{WORK}/models/yolov8x-seg_3class_best.pt")
swin = timm.create_model("swin_tiny_patch4_window7_224", pretrained=False, num_classes=3)
swin.load_state_dict(torch.load(f"{WORK}/models/swin_tiny_masked.pth", map_location=DEV)); swin = swin.to(DEV).eval()
cnx = timm.create_model("convnext_large", pretrained=False, num_classes=3)
cnx.load_state_dict(torch.load(f"{WORK}/models/convnext_large_unmasked.pth", map_location=DEV)); cnx = cnx.to(DEV).eval()
data = [cv2.imread(f) for f in glob.glob("/content/burn_yolo_seg/3class/test/images/*")[:60]]

def bench(fn, warm=8):
    for d in data[:warm]: fn(d)
    torch.cuda.synchronize(); t = time.time()
    for d in data: fn(d)
    torch.cuda.synchronize(); return 1000 * (time.time() - t) / len(data)
def clf_fn(model):
    def g(bgr):
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB); x = tfm(False)(Image.fromarray(rgb)).unsqueeze(0).to(DEV)
        with torch.no_grad(): model(x)
    return g
def pipe_fn(bgr):
    r = yolo1(bgr, imgsz=640, conf=0.05, verbose=False)[0]; rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    if r.masks is not None and len(r.boxes) > 0:
        cf = r.boxes.conf.cpu().numpy(); mk = r.masks.data[int(cf.argmax())].cpu().numpy()
        mk = cv2.resize(mk, (rgb.shape[1], rgb.shape[0])); rgb = rgb * (mk > 0.1).astype(np.uint8)[:, :, None]
    x = tfm(False)(Image.fromarray(rgb.astype(np.uint8))).unsqueeze(0).to(DEV)
    with torch.no_grad(): swin(x)

T = {"YOLO localiser (1-class)": bench(lambda b: yolo1(b, imgsz=640, conf=0.05, verbose=False)),
     "Standalone YOLOv8-seg (3-class)": bench(lambda b: yolo3(b, imgsz=640, verbose=False)),
     "Swin-Tiny classifier": bench(clf_fn(swin)),
     "ConvNeXt-L classifier": bench(clf_fn(cnx)),
     "Full pipeline (loc->mask->Swin)": bench(pipe_fn)}
print("=== per-image inference time (A100, imgsz 640, batch 1) ===")
for k, v in T.items(): print(f"  {k:34s}: {v:6.1f} ms  ({1000/v:4.0f} img/s)")
json.dump(T, open(f"{WORK}/results/timing_results.json", "w"), indent=2)
print("saved -> timing_results.json")

=== per-image inference time (A100, imgsz 640, batch 1) ===
  YOLO localiser (1-class)          :   15.4 ms  (  65 img/s)
  Standalone YOLOv8-seg (3-class)   :   15.1 ms  (  66 img/s)
  Swin-Tiny classifier              :   23.7 ms  (  42 img/s)
  ConvNeXt-L classifier             :   25.8 ms  (  39 img/s)
  Full pipeline (loc->mask->Swin)   :   42.3 ms  (  24 img/s)
saved -> timing_results.json


---
## Section 14 · Paired significance (McNemar) + export proof
Paired McNemar test (classifier vs robust pipeline on the *same* images) for internal + external, saves per-image predictions, and bundles all figures + result JSONs into `benchmark2_proof.zip` on Drive for the manuscript/Zenodo.

In [ ]:
# ===== SECTION 14 · McNemar paired significance + export proof zip =====
import os, glob, json, shutil, numpy as np, cv2, torch, timm
from PIL import Image
from ultralytics import YOLO
from collections import Counter
from scipy.stats import binomtest
WORK = "/content/drive/MyDrive/Burn-Benchmark2"
yolo1 = YOLO(f"{WORK}/models/yolov8x-seg_1class_best.pt")
def load(a, f):
    m = timm.create_model(a, pretrained=False, num_classes=3); m.load_state_dict(torch.load(f"{WORK}/models/{f}", map_location=DEV)); return m.to(DEV).eval()
swin = load("swin_tiny_patch4_window7_224", "swin_tiny_masked.pth"); cnx = load("convnext_large", "convnext_large_unmasked.pth")
def true_deg(l):
    c = [int(x.split()[0]) for x in open(l) if x.split()]; return Counter(c).most_common(1)[0][0] if c else None
def clf(m, bgr):
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB); x = tfm(False)(Image.fromarray(rgb)).unsqueeze(0).to(DEV)
    with torch.no_grad(): return int(m(x).argmax(1))
def pipe(bgr, conf=0.05):
    r = yolo1(bgr, imgsz=640, conf=conf, verbose=False)[0]; rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    if r.masks is None or len(r.boxes) == 0: img = rgb
    else:
        cf = r.boxes.conf.cpu().numpy(); mk = r.masks.data[int(cf.argmax())].cpu().numpy(); mk = cv2.resize(mk, (rgb.shape[1], rgb.shape[0])); img = rgb * (mk > 0.1).astype(np.uint8)[:, :, None]
    x = tfm(False)(Image.fromarray(img.astype(np.uint8))).unsqueeze(0).to(DEV)
    with torch.no_grad(): return int(swin(x).argmax(1))
def mcnemar(idir, ldir, tag):
    b = c = 0; rows = []
    for im in glob.glob(f"{idir}/*"):
        base = os.path.splitext(os.path.basename(im))[0]; lab = f"{ldir}/{base}.txt"
        if not os.path.exists(lab): continue
        td = true_deg(lab)
        if td is None: continue
        bgr = cv2.imread(im)
        if bgr is None: continue
        pc = clf(cnx, bgr); pp = pipe(bgr); cc = int(pc == td); cp = int(pp == td)
        b += int(cc and not cp); c += int(cp and not cc)
        rows.append({"img": os.path.basename(im), "true": td, "clf": pc, "pipe": pp})
    p = binomtest(min(b, c), b + c, 0.5).pvalue if (b + c) > 0 else 1.0
    json.dump(rows, open(f"{WORK}/results/preds_{tag}.json", "w"))
    print(f"McNemar {tag}: classifier-only-correct(b)={b}, pipeline-only-correct(c)={c}, discordant={b+c}, exact p={p:.4f}")
    return {"classifier_only_correct": b, "pipeline_only_correct": c, "exact_p": p, "n_discordant": b + c}
mc = {"internal": mcnemar("/content/burn_yolo_seg/3class/test/images", "/content/burn_yolo_seg/3class/test/labels", "internal"),
      "external": mcnemar("/content/external/images", "/content/external/labels", "external")}
json.dump(mc, open(f"{WORK}/results/mcnemar_results.json", "w"), indent=2)
EXP = "/content/proof"; shutil.rmtree(EXP, ignore_errors=True); os.makedirs(EXP)
shutil.copytree(f"{WORK}/figures", f"{EXP}/figures"); shutil.copytree(f"{WORK}/results", f"{EXP}/results")
shutil.make_archive(f"{WORK}/benchmark2_proof", "zip", EXP)
print("\nzipped -> Burn-Benchmark2/benchmark2_proof.zip |", os.path.getsize(f"{WORK}/benchmark2_proof.zip") // 1024, "KB")

McNemar internal: classifier-only-correct(b)=20, pipeline-only-correct(c)=18, discordant=38, exact p=0.8714
McNemar external: classifier-only-correct(b)=54, pipeline-only-correct(c)=40, discordant=94, exact p=0.1797

zipped -> Burn-Benchmark2/benchmark2_proof.zip | 6322 KB


---
## Section 15 · Fairness fix — standalone YOLO at the same low threshold
The robust pipeline used conf=0.05, but the standalone YOLOv8-seg baseline was evaluated at YOLO's default 0.25 (auto-failing when it found nothing). For a fair benchmark, re-evaluate it at **both** 0.25 and 0.05 on internal + external, so every approach gets its best honest chance.

In [ ]:
# ===== SECTION 15 · FAIR STANDALONE YOLO (low threshold, matching the pipeline) =====
import os, glob, json, numpy as np, cv2
from ultralytics import YOLO
from collections import Counter
from sklearn.metrics import balanced_accuracy_score
WORK = "/content/drive/MyDrive/Burn-Benchmark2"
yolo3 = YOLO(f"{WORK}/models/yolov8x-seg_3class_best.pt")
def true_deg(l):
    c = [int(x.split()[0]) for x in open(l) if x.split()]; return Counter(c).most_common(1)[0][0] if c else None
def ypred(bgr, conf):
    r = yolo3(bgr, imgsz=640, conf=conf, verbose=False)[0]
    if r.boxes is None or len(r.boxes) == 0: return -1
    cf = r.boxes.conf.cpu().numpy(); return int(r.boxes.cls.cpu().numpy()[cf.argmax()])
def evalset(idir, ldir, conf):
    yt, pp, nd = [], [], 0
    for im in glob.glob(f"{idir}/*"):
        b = os.path.splitext(os.path.basename(im))[0]; lab = f"{ldir}/{b}.txt"
        if not os.path.exists(lab): continue
        td = true_deg(lab)
        if td is None: continue
        bgr = cv2.imread(im)
        if bgr is None: continue
        p = ypred(bgr, conf); nd += int(p < 0); yt.append(td); pp.append(p)
    yt, pp = np.array(yt), np.array(pp)
    return 100 * float((pp == yt).mean()), 100 * balanced_accuracy_score(yt, np.where(pp < 0, 99, pp)), len(yt), nd
res = {}
sets = {"internal": ("/content/burn_yolo_seg/3class/test/images", "/content/burn_yolo_seg/3class/test/labels"),
        "external": ("/content/external/images", "/content/external/labels")}
for tag, (idir, ldir) in sets.items():
    for conf in [0.25, 0.05]:
        a, b, n, nd = evalset(idir, ldir, conf)
        res[f"{tag}_conf{conf}"] = {"acc": a, "balanced": b, "n": n, "no_detection": nd}
        print(f"standalone YOLO {tag:8s} conf={conf}: acc {a:.1f}%  bal {b:.1f}%  ({nd} no-detection)")
json.dump(res, open(f"{WORK}/results/standalone_yolo_thresholds.json", "w"), indent=2)
print("saved -> standalone_yolo_thresholds.json")